apiVersion: v1
kind: Job
metadata:
  name: database-scripts-job
  labels:
    app: database-scripts
spec:
  template:
    metadata:
      name: database-scripts-pod
      labels:
        app: database-scripts
    spec:
      containers:
        - name: database-scripts-container
          image: docker.io/bhavnabatra1990/employee:1
          command: ["./databasescript.sh"]
          env:
            - name: SA_HOST
              valueFrom:
                configMapKeyRef:
                name: appsettings
                key: host
            - name: SA_USER
              valueFrom:
                configMapKeyRef:
                name: appsettings
                key: username
            - name: SA_PASSWORD
              valueFrom:
                secretKeyRef:
                name: mssql-secret
                key: SA_PASSWORD
            - name: SA_DATABASE
              valueFrom:
                configMapKeyRef:
                name: appsettings
                key: database
      restartPolicy: Never


