apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-webapi-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-webapi
  template:
    metadata:
      labels:
        app: my-webapi
    spec:
      containers:
        - name: my-webapi-container
          image: docker.io/bhavnabatra1990/employee:1
          ports:
            - containerPort: 80